name: lovespot
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^2.5.0  # Updated to be compatible with firebase_storage and firebase_messaging
  firebase_auth: ^4.1.5
  firebase_database: ^10.0.1
  cloud_firestore: ^4.1.4
  firebase_storage: ^11.0.11  # Ensure version compatibility with firebase_core
  firebase_messaging: 14.7.10  # Compatible version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
